### ISSUE TITLE
Not mobile responsive

### ISSUE THREAD

**Issue by ramz90** [AdamGardelov/ledighetskalkylatorn#1]
This is an **ISSUE**!

**Comment by AdamGardelov** [comment]
Ok i will work as hard as i can until this is resolved. Im so sorry.

**Comment by gusjak** [comment]
Issue is solved, but need super administrative permission to push changes to project. So sorry.

**Comment by ramz90** [comment]
@gusjak Absolutely, we're thrilled to announce that we're working diligently to make sure the super administrative permission person allows you to push changes to the project. 🚀🎉 Your dedication and efforts are greatly appreciated! 🙌🙏😄👏💪 You're doing an amazing job, and we're here to support you all the way! 🌟👍
